//
// Created by LASKAV on 19.02.2023.
//

#ifndef PERSONAL_FINANCE_MANAGEMENT_CLASS_FINANCE_H
#define PERSONAL_FINANCE_MANAGEMENT_CLASS_FINANCE_H

#endif //PERSONAL_FINANCE_MANAGEMENT_CLASS_FINANCE_H
