//
// Created by LASKAV on 19.02.2023.
//

#ifndef PERSONAL_FINANCE_MANAGEMENT_STRUCT_FINANC_H
#define PERSONAL_FINANCE_MANAGEMENT_STRUCT_FINANC_H

#endif //PERSONAL_FINANCE_MANAGEMENT_STRUCT_FINANC_H
